language: java

jdk:
  - openjdk11

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=jp.try0.wicket:wicket-izitoast-parent -Dsonar.organization=try0-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login="$SONAR_SECURE"
